server:
  port: 8080

spring:
  cache:
    type: redis

  redis:
    host: 112.74.108.223
    port: 6379
    password: 123456

#?????????
    client-type: lettuce

#    jedis:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 0
#        max-wait: -1ms

    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms



# ????????????????????
#  spring.redis.lettuce.pool.max-active = 10
#
#  # ???????????
#  spring.redis.lettuce.pool.max-idle = 10
#
#  # ???????????
#  spring.redis.lettuce.pool.min-idle = 0
#
#  # ???????????????????????
#  spring.redis.lettuce.pool.max-wait= -1ms
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xdclass_redis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl